import mongoose from "mongoose";
import { nanoid } from "nanoid";

const shortUrlSchema = new mongoose.Schema({
    // This defines the schema for the `fullUrl` field, which is a required string field
    fullUrl: {
        type: String,
        required: true
    },
    // This defines the schema for the `shortUrl` field, which is a required string field with a default value of 10 random characters generated by the nanoid library
    shortUrl: {
        type: String,
        required: true,
         unique: true,
        default: () => {
            return nanoid().substring(0, 10);
        },
        
      
    },
    // This defines the `clicks` field within the `shortUrl` object as a number type with a default value of 0
    clicks: {
        type: Number,
        default: 0
    }
},
    {
        // This configures the schema to include timestamps, which automatically add a `createdAt` and `updatedAt` timestamp to every document
        timestamps: true // Saves createdAt and updatedAt as dates. CreatedAt
    })


    export const urlModel = mongoose.model("ShortUrl",shortUrlSchema)